spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: mservicet
      port: ${MONGODB_SERVICE_INTERNAL_DEV_PORT}
      authentication-database: admin

server:
  servlet:
    context-path: /mservicet
  port: ${AUTH_SERVICE_DEV_PORT}
