security:
  oauth2:
    client:
      clientId: trainer-service
      clientSecret: ${TRAINER_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:${AUTH_SERVICE_DEV_PORT}/mservicet/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://auth-service:${AUTH_SERVICE_DEV_PORT}/mservicet/users/current

spring:
  data:
    mongodb:
      host: trainer-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: mservicet
      port: ${MONGODB_SERVICE_INTERNAL_DEV_PORT}
      authentication-database: admin

server:
  servlet:
    context-path: /trainers
  port: ${TRAINER_SERVICE_DEV_PORT}